// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8DD4v51H6LDWRu4LAbVrxSZ0sMJ2FBLA',
    appId: '1:433811686263:web:d18110afe09f12a7d55772',
    messagingSenderId: '433811686263',
    projectId: 'vit-complaint-management',
    authDomain: 'vit-complaint-management.firebaseapp.com',
    storageBucket: 'vit-complaint-management.appspot.com',
    measurementId: 'G-4HLMCY069R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM5nBoyB3lKAQwcdYBnppwVwlW9dChuXs',
    appId: '1:433811686263:android:450ea68b0815ae5ed55772',
    messagingSenderId: '433811686263',
    projectId: 'vit-complaint-management',
    storageBucket: 'vit-complaint-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgUeYdUWj4i61S6P6yygltxXbcqkFWmY8',
    appId: '1:433811686263:ios:18d8424008ef012fd55772',
    messagingSenderId: '433811686263',
    projectId: 'vit-complaint-management',
    storageBucket: 'vit-complaint-management.appspot.com',
    iosClientId:
        '433811686263-ftgql9m1iq39l5ikpj41f9ce4e982o2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgUeYdUWj4i61S6P6yygltxXbcqkFWmY8',
    appId: '1:433811686263:ios:18d8424008ef012fd55772',
    messagingSenderId: '433811686263',
    projectId: 'vit-complaint-management',
    storageBucket: 'vit-complaint-management.appspot.com',
    iosClientId:
        '433811686263-ftgql9m1iq39l5ikpj41f9ce4e982o2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitManagement',
  );
}
